import { FACTS, MOQ_SHORT, CERTIFICATION_NAMES, COLLABORATION_MODES } from './facts'

export const SITE_FACTS = {
  warehouseM2: FACTS.warehouseM2,
  workers: FACTS.workers,
  annualCapacity: FACTS.annualCapacity,
  moq: {
    trialStandard: MOQ_SHORT.pilot,
    standardRun: MOQ_SHORT.standard,
    customMould: MOQ_SHORT.custom,
    existingPlatform: MOQ_SHORT.existing,
  },
  moqNote: FACTS.moqNote,
  moqExplanation: FACTS.moqExplanation,
  materialRollNote: FACTS.materialRollNote,
  collaborationModes: COLLABORATION_MODES,
  leadTime: FACTS.leadTime,
  leadTimeDetail: '',
  sampleTime: FACTS.sampleTime,
  cncAccuracy: FACTS.cncAccuracy,
  rfPower: FACTS.rfPower,
  dropStitchPsi: '',
  evaHardness: FACTS.evaHardness,
  assemblyChecklist: FACTS.assemblyChecklist,
  pressureTest: FACTS.pressureTest,
  pressureReject: FACTS.pressureReject,
  traceabilityRet: FACTS.traceabilityRet,
  certifications: CERTIFICATION_NAMES,
  exportCountries: FACTS.exportCountries,
  workshops: FACTS.workshops,
  productionLines: FACTS.productionLines,
  monthlyCapacity: FACTS.monthlyCapacity,
  ndaWindow: FACTS.ndaWindow,
  qualityGates: FACTS.qualityGates,
  thirdPartyInspectors: [],
  samplingStandard: '',
  peakSeason: FACTS.peakSeason,
  social: FACTS.social,
  contact: FACTS.contact,
  boilerplate: FACTS.boilerplate,
  tagline: FACTS.tagline,
  taglineEs: FACTS.taglineEs,
  notRob: FACTS.notRob,
}

export const HERO_CONTENT = {
  en: {
    kicker: '',
    titlePre: '',
    titleAccent: '',
    titlePost: '',
    sub: '',
    ctaPrimary: '',
    ctaSecondary: '',
    ctaTertiary: '',
    ctaQuartiary: '',
    ctaMicro: '',
    stats: [],
    mockupLabel: '',
    mockupBrand: '',
    mockupHint: '',
    heroNote: FACTS.moqNote,
    float1: { value: '', label: '' },
    float2: { value: FACTS.leadTime, label: '' },
  },
  es: {
    kicker: '',
    titlePre: '',
    titleAccent: '',
    titlePost: '',
    sub: '',
    ctaPrimary: '',
    ctaSecondary: '',
    ctaTertiary: '',
    ctaQuartiary: '',
    ctaMicro: '',
    stats: [],
    mockupLabel: '',
    mockupBrand: '',
    mockupHint: '',
    heroNote: FACTS.moqNoteEs,
    float1: { value: '', label: '' },
    float2: { value: FACTS.leadTime, label: '' },
  },
}

export const siteConfig = {
  facts: SITE_FACTS,
  hero: HERO_CONTENT,
}

export type { Locale } from '@/features/i18n/locale'
