/**
 * ResponsiveImage — renders a <picture> element with srcset for multiple
 * widths and formats (AVIF + WebP). Works with free Cloudflare R2 which
 * has no on-the-fly image resizing — variants are pre-generated by
 * scripts/process-responsive-images.mjs and uploaded to R2.
 *
 * Usage:
 *   <ResponsiveImage
 *     src="https://assets.agrospear.com/images/agrochemical/products/hero.avif"
 *     alt="Hero image"
 *     width={1920}
 *     height={1080}
 *     sizes="100vw"
 *   />
 *
 * The component automatically generates srcSet entries for widths:
 * 480, 768, 1024, 1280, and the original size.
 *
 * If the image is small (< 600px wide) or no responsive variants exist,
 * it falls back to a simple <img> tag.
 */

import * as React from 'react'

interface ResponsiveImageProps extends React.ComponentProps<'img'> {
  /** Original image URL (the largest size) */
  src: string
  /** Alt text */
  alt: string
  /** Original natural width */
  width: number
  /** Original natural height */
  height: number
  /** CSS sizes attribute — defaults to "100vw" */
  sizes?: string
  /** Whether to add fetchpriority="high" (for above-the-fold images) */
  fetchPriority?: 'high' | 'low' | 'auto'
  /** Whether to disable lazy loading (for hero/LCP images) */
  eager?: boolean
}

// Responsive width breakpoints that match process-responsive-images.mjs
const RESPONSIVE_WIDTHS = [480, 768, 1024, 1280]

function buildSrcSet(baseSrc: string, naturalWidth: number): string {
  // Only generate srcSet if the image is large enough to benefit
  if (naturalWidth < 600) return ''

  const parts: string[] = []

  for (const w of RESPONSIVE_WIDTHS) {
    if (w >= naturalWidth) break
    // Replace the extension with the responsive variant name
    // e.g., hero.avif → hero-480.avif
    const variant = baseSrc.replace(/\.(avif|webp|jpg|jpeg|png)$/i, `-${w}.$1`)
    parts.push(`${variant} ${w}w`)
  }

  // Add the original as the largest
  parts.push(`${baseSrc} ${naturalWidth}w`)

  return parts.join(', ')
}

export function ResponsiveImage({
  src,
  alt,
  width,
  height,
  sizes = '100vw',
  fetchPriority,
  eager,
  className,
  ...rest
}: ResponsiveImageProps) {
  // Generate AVIF and WebP srcSet from the primary src
  const srcExt = src.match(/\.(avif|webp|jpg|jpeg|png)$/i)?.[1]?.toLowerCase() ?? 'avif'

  // Build the other format URL (AVIF ↔ WebP)
  const otherExt = srcExt === 'avif' ? 'webp' : 'avif'
  const otherSrc = src.replace(new RegExp(`\\.${srcExt}$`, 'i'), `.${otherExt}`)

  const primarySrcSet = buildSrcSet(src, width)
  const otherSrcSet = buildSrcSet(otherSrc, width)

  // If no responsive variants possible (small image), use plain <img>
  if (!primarySrcSet) {
    return (
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
        fetchPriority={fetchPriority}
        className={className}
        {...rest}
      />
    )
  }

  return (
    <picture>
      {/* AVIF source (best compression) */}
      {srcExt === 'avif' ? (
        <source srcSet={primarySrcSet} type="image/avif" sizes={sizes} />
      ) : (
        <source srcSet={otherSrcSet} type="image/avif" sizes={sizes} />
      )}
      {/* WebP source */}
      {srcExt === 'webp' ? (
        <source srcSet={primarySrcSet} type="image/webp" sizes={sizes} />
      ) : (
        <source srcSet={otherSrcSet} type="image/webp" sizes={sizes} />
      )}
      {/* Fallback img */}
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={eager ? 'eager' : 'lazy'}
        decoding="async"
        fetchPriority={fetchPriority}
        className={className}
        {...rest}
      />
    </picture>
  )
}
