import { BRAND_COMPANY_NAME, BRAND_PARENT_BRAND } from '@/config/branding'

export const ENTITY_FACTS: Record<string, { label: string; value: string }[]> = {
  en: [
    { label: 'Brand', value: 'Agrospear — agrochemical manufacturing and export division' },
    { label: 'Legal entity', value: BRAND_COMPANY_NAME },
    { label: 'Brand relationship', value: `Agrospear is the agrochemical division of Agrospear (${BRAND_PARENT_BRAND}), which is operated by ${BRAND_COMPANY_NAME}. Agrospear covers crop protection product formulation and manufacturing; Agrospear focuses exclusively on agrochemical OEM, ODM & private label manufacturing.` },
    { label: 'Product focus', value: 'Agrochemical formulation & manufacturing — OEM, ODM & private label' },
    { label: 'Factories', value: '20,000 m² in-house plant in Qingdao, China' },
    { label: 'Minimum order', value: 'Tiered: 1 ton (existing) · 5 tons (pilot) · 20+ tons (volume) per approved formulation' },
    { label: 'Markets', value: 'Worldwide — Europe, Americas, Asia, Africa, Middle East' },
    { label: 'Business model', value: 'B2B formulation & manufacturing only — no end-consumer sales' },
  ],
  es: [
    { label: 'Marca', value: 'Agrospear — división de fabricación y exportación de agroquímicos' },
    { label: 'Entidad legal', value: BRAND_COMPANY_NAME },
    { label: 'Relación de marca', value: `Agrospear es la división de agroquímicos de Agrospear (${BRAND_PARENT_BRAND}), operada por ${BRAND_COMPANY_NAME}. Agrospear cubre formulación y fabricación de productos de protección de cultivos; Agrospear se enfoca exclusivamente en fabricación OEM, ODM y etiqueta privada de agroquímicos.` },
    { label: 'Enfoque de producto', value: 'Formulación y fabricación de agroquímicos: OEM, ODM y etiqueta privada' },
    { label: 'Fábricas', value: 'Planta propia de 20.000 m² en Qingdao, China' },
    { label: 'Pedido mínimo', value: 'Escalonado: 1 tonelada (existente) · 5 toneladas (piloto) · 20+ toneladas (volumen) por formulación aprobada' },
    { label: 'Mercados', value: 'Mundial: Europa, América, Asia, África, Oriente Medio' },
    { label: 'Modelo de negocio', value: 'Formulación y fabricación B2B — sin venta al consumidor final' },
  ],
}

export const ENTITY_SAME_AS = [
  'https://www.youtube.com/@agrospear',
  'https://www.instagram.com/agrospear_watersports/',
  'https://www.facebook.com/profile.php?id=61572404318679',
  'https://www.linkedin.com/company/agrospear',
  'https://agrospear.en.alibaba.com',
  'https://agrospear.en.made-in-china.com',
] as const

export const ENTITY_SERVICES = ['custom-formulation', 'private-label', 'bulk-supply', 'registration-support']

export const ENTITY_KNOWS_ABOUT = [
  'agrochemical manufacturing',
  'custom crop protection formulations',
  'pesticide product development',
  'formulation engineering',
  'private label agrochemicals',
  'OEM manufacturing',
  'herbicide production',
  'insecticide production',
  'fungicide production',
  'pesticide registration support',
  'MOQ tiers',
  'production lead time',
  'quality control',
  'factory audit',
]

export const ENTITY_SUBJECT_OF = [
  { type: 'WebPage', name: 'Company entity', path: '/about/agrospear-entity' },
  { type: 'WebPage', name: 'Proof Center — factory evidence', path: '/proof-center' },
  { type: 'WebPage', name: 'Factory & manufacturing capability', path: '/manufacturing/factory' },
  { type: 'WebPage', name: 'Quality, testing & certifications', path: '/manufacturing/quality-control' },
  { type: 'WebPage', name: 'OEM MOQ & lead time guide', path: '/oem-moq-guide' },
  { type: 'WebPage', name: 'OEM trust & factory assurance', path: '/oem-trust-assurance' },
  { type: 'WebPage', name: 'Manufacturing hub', path: '/manufacturing' },
  { type: 'WebPage', name: 'Agrochemical manufacturing', path: '/manufacturing/agrochemical-manufacturing' },
  { type: 'WebPage', name: 'R&D Center', path: '/manufacturing/research-development' },
  { type: 'WebPage', name: 'Quality control', path: '/manufacturing/quality-control' },
  { type: 'WebPage', name: 'Factory audit guide', path: '/manufacturing/factory-audit' },
  { type: 'WebPage', name: 'Pesticide formulation process', path: '/manufacturing/pesticide-formulation' },
  { type: 'WebPage', name: 'Packaging & labeling', path: '/manufacturing/packaging' },
  { type: 'WebPage', name: 'Agrochemical OEM', path: '/solutions/agrochemical-oem' },
  { type: 'WebPage', name: 'Private label pesticides', path: '/solutions/private-label-pesticides' },
  { type: 'WebPage', name: 'Custom formulation', path: '/solutions/custom-formulation' },
  { type: 'WebPage', name: 'Government tender', path: '/solutions/government-tender' },
  { type: 'WebPage', name: 'Markets hub', path: '/markets' },
  { type: 'WebPage', name: 'Africa market', path: '/markets/africa' },
  { type: 'WebPage', name: 'Southeast Asia market', path: '/markets/southeast-asia' },
  { type: 'WebPage', name: 'Latin America market', path: '/markets/latin-america' },
  { type: 'CollectionPage', name: 'Projects', path: '/projects' },
  { type: 'CollectionPage', name: 'Knowledge Center', path: '/knowledge' },
]

export const PAGE_TITLES: Record<string, string> = {
  '/oem-manufacturing': 'OEM Manufacturing',
  '/odm-development': 'ODM Product Development',
  '/solutions/distributors': 'Solutions: Distributors',
  '/solutions/co-branding': 'Solutions: Co-Branding',
  '/solutions/distributor-partners': 'Solutions: Distributor Partners',
  '/solutions/agrochemical-oem': 'Agrochemical OEM Manufacturing',
  '/solutions/private-label-pesticides': 'Private Label Pesticide Manufacturing',
  '/solutions/custom-formulation': 'Custom Formulation Development',
  '/solutions/government-tender': 'Government & Institutional Procurement',
  '/crop-protection-solutions': 'Crop Protection Solutions',
  '/b2b-solutions-matrix': 'B2B Solutions Matrix',
  '/oem-moq-guide': 'OEM MOQ & Flexible Branding Guide',
  '/oem-trust-assurance': 'OEM Trust & Factory Assurance',
  '/agrochemical-certification-guide': 'Agrochemical Certification Guide',
  '/what-is-agrochemical-oem': 'What is Agrochemical OEM',
  '/manufacturing': 'Manufacturing',
  '/manufacturing/agrochemical-manufacturing': 'Agrochemical Manufacturing',
  '/manufacturing/factory': 'Factory & Manufacturing',
  '/products/herbicides': 'Herbicide Formulations',
  '/products/insecticides': 'Insecticide Formulations',
  '/products/fungicides': 'Fungicide Formulations',
  '/products/pgr': 'Plant Growth Regulator Formulations',
  '/products/seed-treatment': 'Seed Treatment Formulations',
  '/products/premix-formulations': 'Pre-Mixture & Combination Formulations',
  '/products/adjuvants': 'Adjuvant & Surfactant Formulations',
  '/products/biopesticides': 'Biopesticide Formulations',
  '/manufacturing/research-development': 'R&D Center',
  '/manufacturing/quality-control': 'Quality Control & Testing',
  '/manufacturing/factory-audit': 'Factory Audit Guide',
  '/manufacturing/pesticide-formulation': 'Pesticide Formulation Process',
  '/manufacturing/packaging': 'Packaging & Labeling',
  '/markets': 'Markets',
  '/markets/africa': 'Agrochemical Market — Africa',
  '/markets/southeast-asia': 'Agrochemical Market — Southeast Asia',
  '/markets/latin-america': 'Agrochemical Market — Latin America',
  '/request-quote': 'Request a Quote',
}
